
CREATE SEQUENCE  dbadm.dbadm$seq
MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 1
NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

GRANT SELECT ON dbadm.dbadm$seq TO colapp;

# table DBADM.SYS_LOG

GRANT SELECT, INSERT ON dbadm.sys_log TO colapp;
GRANT SELECT ON dbadm.session_info_v TO colapp;

DROP TABLE dbadm.sys_log;
CREATE TABLE DBADM.SYS_LOG (
	TIMEPOINT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	DATABASE_TYPE VARCHAR2(126),
	DATABASE_NAME VARCHAR2(126),
	SID NUMBER,
	PID NUMBER,
	USER_NAME VARCHAR2(126),
	SCHEMA_NAME VARCHAR2(126),
	MODUL_CODE VARCHAR2(126),
	TYPE_CODE VARCHAR2(126),
	PARAMETER VARCHAR2(4000),
	STEP_CODE VARCHAR2(126),
	STATUS_CODE VARCHAR2(48) DEFAULT 'SUCCESS',
	SQL_COMMAND CLOB,
	ERROR_NUMBER NUMBER,
	ERROR_MESSAGE CLOB,
	ID NUMBER DEFAULT dbadm.dbadm$seq.nextval,
	CONSTRAINT SYS_C0013624 CHECK ("TIMEPOINT" IS NOT NULL),
	CONSTRAINT SYS_LOG_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_LOG_PK ON DBADM.SYS_LOG (ID);

# create view DBADM.SESSION_INFO_V
@sys
grant select on sys.v_$instance to dbadm WITH GRANT OPTION;
grant select on sys.v_$database to dbadm WITH GRANT OPTION;
drop view dbadm.session_info_v;
create or replace view dbadm.session_info_v
as
SELECT SYS_CONTEXT ('USERENV', 'INSTANCE_NAME') as current_database,
       SYS_CONTEXT ('USERENV', 'SESSION_USER') as current_user,
       (select 'Oracle '||version_full from v$instance) as version,
       SYS_CONTEXT ('USERENV', 'SID') as sid
FROM dual;